drop table if exists booking;
drop table if exists requests;
drop table if exists comments;
drop table if exists items;
drop table if exists users;


CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_email UNIQUE (email)
);
CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(4000)                           NOT NULL,
    is_available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL
        CONSTRAINT items_users_fk REFERENCES users,
    CONSTRAINT pk_items PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_booking PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id    BIGINT                                  NOT NULL
        CONSTRAINT bookings_items_id_fk
            REFERENCES items,
    booker_id  BIGINT                                  NOT NULL
        CONSTRAINT bookings_users_id_fk
            REFERENCES users,
    status     VARCHAR                                 NOT NULL
);
CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        CONSTRAINT pk_comment primary key,
    text      VARCHAR(500)                            NOT NULL,
    item_id   BIGINT                                  NOT NULL
        CONSTRAINT comments_items__fk
            REFERENCES items,
    author_id BIGINT                                  NOT NULL
        CONSTRAINT comments_users_id_fk
            REFERENCES users,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(500),
    user_id     BIGINT REFERENCES users (id),
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
